### ISSUE TITLE
Inserting Beeps Into A Script Causes The Script To Break

### ISSUE THREAD

**Issue by mtri** [nirgoren/Eddienput#10]
I started playing around with this software today and was excited to try out using the beep feature to better understand execution timing for button presses in combos. I made the following script for Millia Rage in GGXAC+R:

configs\gg.json
[2] S W10 H ]2[ W20 9 W18 S W12 H W16 [6] ]6[ W5 [6] ]6[ W15 [2] [H] W60 ]2[ ]H[
S W12 [2] H ]2[ W20 9 W12 S W10 H W16 [6] ]6[ W5 [6] ]6[ W15 [2] [H] W50 ]2[ ]H[
S W12 [2] H ]2[ W20 9 W12 S W10 H W16 [6] ]6[ W5 [6] ]6[ W15 [2] [H] W60 ]2[ ]H[
2 3 6 H

And after some troubleshooting, it works great! In order to better understand what the timing would be to hit buttons on an actual controller, I inserted beep sounds into the script to see if I could get audio queues for when to press the buttons for execution:

configs\gg.json
[2] S beep W10 H ]2[ W20 beep 9 W18 beep S W12 beep H W16 beep [6] ]6[ W5 [6] ]6[ W15 beep [2] [H] W60 beep ]2[ ]H[ 
S W12 beep [2] H ]2[ W20 beep 9 W12 beep S W10 beep H W16 beep [6] ]6[ W5 [6] ]6[ W15 beep [2] [H] W50 beep ]2[ ]H[
S beep W12 [2] H beep ]2[ W20 9 beep W12 S beep W10 H beep W16 [6] ]6[ W5 [6] ]6[ W15 beep [2] [H] W60 beep ]2[ ]H[
beep 2 3 6 H

This immediately resulted in the combo breaking seemingly because the timings were thrown off as if the beeps were button presses themselves taking up space in the timeline.

It would be amazing if there was an easy way to play a beep on button press without it messing up the timings of the combos AND/OR beeps themselves do not affect the script and simply play audio at the designated time.

(PS Great work I'm subscribing to the Patreon)

**Comment by nirgoren** [comment]
You need to add the beeps to the frame you want them to play like so:
`S+beep`
or for held buttons:
`[6]+beep`
That way you get them at the exact time the button should be presses and you don't introduce any new frames to the script (which would break it)
