### ISSUE TITLE
Tekken notations

### ISSUE THREAD

**Issue by CollinWest** [nirgoren/Eddienput#17]
Hi, I am using this for Tekken and I think the tekken.json config could be updated to better reflect how inputs are written for that game.

Tekken notation does not use numpad notation, numbers in Tekken represent the limbs (1 is LP, 2 is RP, 3 is LK, 4 is RK). I was able to quickly add them myself in the JSON as well as fix the motion input macros and it seems to work great.

The "RA" button can also be removed because generally people don't use that macro, every character has a normal input like d1+2 to do their rage art. 

I have my modified tekken.json in this pastebin with the changes I mentioned if you want to take a look at it and possibly commit it. This project would really benefit Tekken players if it took off since this game has so many moves and matchups to play against. Thanks for this!

https://pastebin.com/QXPKtzyq

**Comment by cormick9** [comment]
I also made a fork if you would like me to continue working on the Tekken side of this. There are still some things unique to Tekken like sidesteps on different sides and such. If I have some free time I could look at adding macros for those.
https://github.com/cormick9/Eddienput/tree/tekken
