### ISSUE TITLE
[Request] Buttons next to bind listings to allow control per instance

### ISSUE THREAD

**Issue by Waistless** [nirgoren/Eddienput#20]
Hi,

I've been making great use of this tool you've created for tool-assisting certain situations in Tekken 7. 

However, I've found the need to use two instances in order to strictly control the inputs of both characters. But it doesn't seem possible to bind several Eddienputs to P1 and P2 without significant hassle, if at all.

For example, in Tekken 7 practice mode:
1.) Open menu, select cpu action controller:
2.) Open Eddienput 1, press Home to bind p1
3.) Open Eddienput 2, Press Home again
4.) Result: Game goes back to menu and undoes the bind attempt.

This seems to happen because I cannot *individually* press home on an individual eddienput, as the hotkey will control both simultaneously.  This is fine and actually what I need for the other binds, but not for pressing start/select.

If each bind in the listing were to have a UI button so that I could manually activate only for the one instance, it would work easily (Tekken 7 does not require focus w/ mouse click for controller inputs to work). 
Another nice feature would be a single bind for Reload Script and Play (or reload script before play when bound to F5), rather than always needing to press the two sequentially for editing and testing.

Hope you get around to implementing my suggestion, this is an amazing tool!

**Comment by nirgoren** [comment]
Thank you for your input - we will consider the case of running two instances of the program at the same time.

**Comment by nirgoren** [comment]
As of v1.1 you can temporarily suppress hotkeys in one Eddienput instance, that way you can individually press home (or any other button) on an Eddienput instance (the one that is currently not suppressed).
